### ISSUE TITLE
Estructura del proyecto

### ISSUE THREAD

**Issue by delucas** [ada-lovelace-progra/Taller-bot-ops#2]
El proyecto a compartir no debe ser el workspace completo, sino sólamente a nivel "proyecto", propiamente dicho. Muevan el `Proyecto-Taller` al directorio raiz, ya que ese es el proyecto `Taller-bot-ops`.

**Comment by FedeMarkoo** [comment]
https://github.com/ada-lovelace-progra/Taller-bot-ops/commit/6314874111071a34b78ab18cb17acd4045345e5d
