### ISSUE TITLE
Ignorar la base de datos en el repo

### ISSUE THREAD

**Issue by delucas** [ada-lovelace-progra/Taller-bot-ops#3]
La base de datos cambia constantemente, por lo que si la ponen bajo control de cambios, estarán haciendo commit constante de este archivo.
Adicionalmente, los datos NO deben ponerse bajo control de versiones, por práctica.

**Comment by FedeMarkoo** [comment]
Las BD que quedan son una para las respuestas del asistente y otra con usuarios de ejemplo para testeo... pero no se van agregar mas usuarios

https://github.com/ada-lovelace-progra/Taller-bot-ops/commit/0a91460429f56b471a2f77e6d7380479e774fdce
