### ISSUE TITLE
Utilizar un mejor patrón para ordenar este resolvedor

### ISSUE THREAD

**Issue by delucas** [ada-lovelace-progra/Taller-bot-ops#8]
El código se vuelve inmanejable. Reducir el uso de switch/if mediante despachos polimórficos.

https://github.com/ada-lovelace-progra/Taller-bot-ops/blob/21579dab5e93d3f2e5bbf8906f33fa96a2a2cfbc/Proyecto-Taller/Asistente/resolvedores/Fecha.java#L23

**Comment by pokengineer** [comment]
se agrego una chain of responsibility con los diferentes metodos de la clase fecha
